### ISSUE TITLE
openpyxl in requirements has moved.

### ISSUE THREAD

**Issue by tommeagher** [pandaproject/panda#941]
This line in the requirements.txt is out of date:
hg+https://bitbucket.org/ericgazoni/openpyxl/@134c257abd1e#egg=openpyxl

The project appears to have moved here: 
hg+https://bitbucket.org/openpyxl/openpyxl/@134c257abd1e#egg=openpyxl

**Comment by JoeGermuska** [comment]
I hadn't seen this, but I encountered the openpyxl problem setting up a Panda for Medill. I fixed it with a pypi dependency instead in e0f0f65

**Comment by zstumgoren** [comment]
+1 even better

**Comment by tommeagher** [comment]
Cleaning up my old issues. Closing this one, thanks to @JoeGermuska & e0f0f65.

Thanks!
